@startuml TelemetryServiceComponents
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(telemetry_boundary, "Телеметрия") {
    ContainerDb(telemetry_db, "Telemetry DB", "Redis", "Хранит текущие показания")

    Component(telemetry_in, "Telemetry in controller", "Spring REST Controller", "Принимает/отдаёт данные от датчиков")
    Component(telemetry_service, "Telemetry Service", "Spring Service", "Обработка телеметрии")
    Component(telemetry_repository, "Telemetry Repository", "Spring Data Redis", "Работа с Redis")
}

Container(api_gateway, "API Gateway", "Любой, с чем работала команда разработки", "Единая точка входа")

Rel(api_gateway, telemetry_in, "POST/GET", "HTTP/REST/JSON")
Rel(telemetry_in, telemetry_service, "Обработка телеметрии", "Java")
Rel(telemetry_service, telemetry_repository, "Запись/чтение из хранилища", "Redis Template")
Rel(telemetry_repository, telemetry_db, "SET/GET", "Redis Protocol")

@enduml